# Default hostname
hostname: localhost

# Running port
port: 3030

# Virtual hosts setup
virtual_hosts:
  - domain: localhost
    # Root folder
    root: www
    # Custom pages
    error_pages:
      - method: 404
        path: pages/404.html
      - method: 500
        path: pages/500.html
